name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      ############################################
      # 1. Récupération du code
      ############################################
      - name: Checkout repository
        uses: actions/checkout@v4

      ############################################
      # 2. Analyse SAST avec CodeQL
      ############################################
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      ############################################
      # 3. Analyse sécurité Python avec Bandit
      ############################################
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r api -ll

      ############################################
      # 4. Scan des dépendances Python (Safety)
      ############################################
      - name: Install Safety
        run: pip install safety

      - name: Dependency vulnerability scan
        run: safety check -r requirements.txt

      ############################################
      # 5. Construction de l'image Docker
      ############################################
      - name: Build Docker Image
        run: docker build -t devsecops-api .

      ############################################
      # 6. Scan de l'image Docker avec Trivy
      ############################################
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-api
          severity: CRITICAL,HIGH
          exit-code: 1
